### ISSUE TITLE
프로젝트 구상

### ISSUE THREAD

**Issue by HyeonIn** [HyeonIn/BankingService#1]
- [x] 사용할 프레임워크 선정
- [x] 개발 순서 결정
- [x] 기능적 요구사항 작성(유즈케이스 다이어그램)

**Comment by HyeonIn** [comment]
개발 순서
- 은행 서비스를 간단하게 파이썬으로만 구현해보고 주요 알고리즘들을 모듈화 한다.
- Django 프레임워크를 사용해서 TUI 기반 서버를 만든다.
- 반응형 웹 페이지를 제작한다.
- 데이터베이스를 연동시켜서 사용자의 정보를 관리한다.

**Comment by unhochoi** [comment]
:thumbsup:
